### ISSUE TITLE
Multiple Roles wont answer or interogate with each other.

### ISSUE THREAD

**Issue by chaincrafter** [turboderp/exui#30]
When i add multiple Roles, only one bot (role) answers. they do not interact with each other. what am i doing wrong?

**Comment by turboderp** [comment]
It's the model that decides which role replies next, so you have to prompt it to begin its reply with `Bot #2:`. E.g. with a question like `What do you think, Bot #2?`. In any case, all the roles have to be introduced in the context somehow, otherwise the model has no reason to predict replies from any particular one. You could try a system prompt like `This is a conversation between Bot #1 and Bot #2`, and then just press enter repeatedly and the two bots should start talking to each other. Another way is to force each bot into the history by editing a few blocks to "prime" the model that way.

**Comment by chaincrafter** [comment]
Thanks. i got it. when i press enter multiple times they talk to each other. Thats fine now. :)
